### ISSUE TITLE
正道的光不应该被污秽之流打败

### ISSUE THREAD

**Issue by ok406lhq** [Snoopy1866/LiTiaotiao-Custom-Rules#10]
加油

**Comment by boobb** [comment]
酷安的人借李跳跳被起诉这个油头把相关话题全清了，
现在知道为什么当年出那事以后大小姐会离开酷安了

**Comment by boobb** [comment]
想请教个事，目前还有类似酷安的简中平台吗？

**Comment by Snoopy1866** [comment]
为什么一定要简中，github不好吗������



***@***.***
 
发件人： boobb
发送时间： 2023-08-24 13:56
收件人： Snoopy1866/LiTiaotiao-Custom-Rules
抄送： Subscribed
主题： Re: [Snoopy1866/LiTiaotiao-Custom-Rules] 正道的光不应该被污秽之流打败 (Issue #10)
想请教个事，目前还有类似酷安的简中平台吗？

**Comment by boobb** [comment]
不是，是我英语比较差😥虽然简中一直是个粪坑……

**Comment by LarryDong** [comment]
有没有哪位朋友能提供下跳跳开发者的联系方式，想以各种力所能及的形式表达下支持与感谢。

**Comment by chenyu-52** [comment]
> 有没有哪位朋友能提供下跳跳开发者的联系方式，想以各种力所能及的形式表达下支持与感谢。

软件中有微信和支付宝的投喂设置，但是不确定是否遭到修改，这点需要大神求证

**Comment by boobb** [comment]
> > 没有哪一位朋友能够提供下跳跳开发者的联系方式，想以各种力所能及的形式表达下支持与感谢。
> 
> 软件中有微信和支付宝的投付设置，但不确定是否接受修改，这需要大神求证

WeChat是这个
![IMG_20230828_171449](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/50999664/07cdde49-60b7-4ced-940e-b343183e608e)

**Comment by boobb** [comment]
你们打开软件
更多/重要提示/支持作者看看对不对
对比一下看看对不对，
我的是在大小姐的官方渠道下载的
@iwanna52 @LarryDong 
联系方式大小姐李跳跳的公众号里面有

**Comment by boobb** [comment]
> > 8月24号的今日热点酷安刻意压了今天李跳跳被起诉这事，还借李跳跳被起诉这个油头把相关话题全清了， 现在知道为什么当年出那事以后大小姐会离开酷安了
> 
> 没有被起诉，只是被投了律师函，其他的类似李跳跳的软件也都被投了律师函

是的没有被起诉，只是收了律师函这里写错了
不过我对酷安还是差评

**Comment by Nightola0227** [comment]
> > > 没有哪一位朋友能够提供下跳跳开发者的联系方式，想以各种力所能及的形式表达下支持与感谢。
> > 
> > 
> > 软件中有微信和支付宝的投付设置，但不确定是否接受修改，这需要大神求证
> 
> WeChat是这个 ![IMG_20230828_171449](https://user-images.githubusercontent.com/50999664/263657262-07cdde49-60b7-4ced-940e-b343183e608e.jpg)

想试着支持一下，然后发现已经被限制交易了。

![Screenshot_20230830_090735](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/125177267/09cef537-3442-4dbe-9521-58c14da1b599)

**Comment by Nightola0227** [comment]
> > > 没有哪一位朋友能够提供下跳跳开发者的联系方式，想以各种力所能及的形式表达下支持与感谢。
> > 
> > 
> > 软件中有微信和支付宝的投付设置，但不确定是否接受修改，这需要大神求证
> 
> WeChat是这个 ![IMG_20230828_171449](https://user-images.githubusercontent.com/50999664/263657262-07cdde49-60b7-4ced-940e-b343183e608e.jpg)

想试着支持一下，然后发现已经被限制交易了。

![Screenshot_20230830_091922](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/125177267/6774fda2-5e92-4e41-bce3-b9604778eecd)

**Comment by boobb** [comment]
> > > > 没有哪一位朋友能够提供下跳跳开发者的联系方式，想以各种力所能及的形式表达下支持与感谢。
> > > 
> > > 
> > > 软件中有微信和支付宝的投付设置，但不确定是否接受修改，这需要大神求证
> > 
> > 
> > WeChat是这个 ![IMG_20230828_171449](https://user-images.githubusercontent.com/50999664/263657262-07cdde49-60b7-4ced-940e-b343183e608e.jpg)
> 
> 想试着支持一下，然后发现已经被限制交易了。
> 
> ![Screenshot_20230830_091922](https://user-images.githubusercontent.com/125177267/264200290-6774fda2-5e92-4e41-bce3-b9604778eecd.png)

又是必胜客干的好事
