### ISSUE TITLE
[适配需求] 京东读书

### ISSUE THREAD

**Issue by hsunxcheung** [Snoopy1866/LiTiaotiao-Custom-Rules#100]
**请注意：基于 bounds 的规则不会被适配**

**京东读书**

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。

**广告界面（提供截图）（可选）**
![Screenshot_2023-09-21-21-49-12-299_com jd app reader](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/145515809/ca153d2d-9cb8-4821-a45e-1458e20ee03a)

**补充信息**
每天第一次打开京东读书的时候，开屏总是有这个摇一摇的广告，李跳跳总是没能跳过，但当天再次打开京东读书的时候，又是可以都跳过。似乎新版本的京东读书才有这个问题。

**Comment by Snoopy1866** [comment]
已通过 gkd 完成适配，建议切换至 gkd。
[#258](https://github.com/gkd-kit/subscription/pull/258)
