### ISSUE TITLE
[适配需求] 公考雷达

### ISSUE THREAD

**Issue by yiwaaaa** [Snoopy1866/LiTiaotiao-Custom-Rules#106]
**App 名称**
公考雷达

**广告界面（提供截图）（可选）**
1.提示更新
![0b76f8c23c5756ad512496d3c4327c5](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/145822247/8b140ca4-c5bd-4561-b140-37e0e5b85212)

**补充信息**
添加任何你认为有助于适配的信息

**Comment by Snoopy1866** [comment]
[#365](https://github.com/gkd-kit/subscription/pull/365)
