### ISSUE TITLE
[适配需求] 网速管家

### ISSUE THREAD

**Issue by yiwaaaa** [Snoopy1866/LiTiaotiao-Custom-Rules#108]
**App 名称**
网速管家

**广告界面（提供截图）（可选）**
1.首页弹窗
![325d2131e746060a142d58c0f079a04](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/145822247/f2438a9b-3f01-4bfe-86eb-7f6f76bf10b8)

**补充信息**
添加任何你认为有助于适配的信息

**Comment by Snoopy1866** [comment]
[#367](https://github.com/gkd-kit/subscription/pull/367)

**Comment by Snoopy1866** [comment]
网速管家无法下载，建议直接在这里传一个安装包。
![a978ea394d092b60c1718ae9a095005](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/45487685/a22861d7-c91f-4f5f-8833-3bd5978972fb)

**Comment by yiwaaaa** [comment]
https://app.sharess.cn/page/app/detail?id=CVxdenePC7MVp7_CQ3VbBg%3D%3D
附件上传有大小限制上传不了

**Comment by yiwaaaa** [comment]
[1695687129744.zip](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/files/12720719/1695687129744.zip)

**Comment by yiwaaaa** [comment]
[1695688947622.zip](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/files/12720856/1695688947622.zip)
