### ISSUE TITLE
[适配需求]华图在线

### ISSUE THREAD

**Issue by yiwaaaa** [Snoopy1866/LiTiaotiao-Custom-Rules#109]
**App 名称**
华图在线

**广告界面（提供截图）（可选）**
![Uploading f220394c0d799a0b7f56f448353aaa7.jpg…]()

**补充信息**
添加任何你认为有助于适配的信息

**Comment by yiwaaaa** [comment]
![f220394c0d799a0b7f56f448353aaa7](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/145822247/37efb7d9-f718-4075-888a-61001c2aa520)

**Comment by Snoopy1866** [comment]
暂未发现此广告，建议上传gkd快照方便适配。https://github.com/gkd-kit/gkd
<img width="5973" alt="GKD快照分享图片教程" src="https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/45487685/f989dd6b-4438-4d66-9209-f1200c48a95a">

**Comment by Snoopy1866** [comment]
[#370](https://github.com/gkd-kit/subscription/pull/370)

**Comment by yiwaaaa** [comment]
今天复现不成功，待有之后再上传快照。

**Comment by yiwaaaa** [comment]
[1695859376940.zip](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/files/12744156/1695859376940.zip)
补充弹窗

**Comment by Snoopy1866** [comment]
- https://github.com/gkd-kit/subscription/pull/452
