### ISSUE TITLE
全部规则在哪看

### ISSUE THREAD

**Issue by koi3378** [Snoopy1866/LiTiaotiao-Custom-Rules#11]

**Comment by Snoopy1866** [comment]
哥们，都来这里了，看看说明文档不用教吧

**Comment by FW27623** [comment]
https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/tree/main?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8

**Comment by sodagreen574** [comment]
都来github了。。看看文档吧

**Comment by DHLlib** [comment]
文档被清了T-T

**Comment by Snoopy1866** [comment]
> 文档被清了T-T

没有呢，链接已更新
