### ISSUE TITLE
[适配需求] 华为运动健康

### ISSUE THREAD

**Issue by yiwaaaa** [Snoopy1866/LiTiaotiao-Custom-Rules#112]
**App 名称** 华为运动健康

**App 包名（可选）**

**广告界面（提供截图）（可选）**
1.发现新版本弹窗
![c7d1bc1f47a711e3eab779b9a936bc8](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/145822247/6e634854-85de-4708-9694-bc5123c37107)

**补充信息**
版本：12.1.7.333

**Comment by Snoopy1866** [comment]
建议提供快照
