### ISSUE TITLE
[适配需求] 智慧生活

### ISSUE THREAD

**Issue by yiwaaaa** [Snoopy1866/LiTiaotiao-Custom-Rules#113]
**App 名称** 智慧生活

**App 包名（可选）** com.huawei.smartthome

**广告界面（提供截图）（可选）**
1.新版本弹窗
![89867b931b278c4354f05d624f23e48](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/145822247/f9a28bba-4fb5-44e5-9c74-037e58226aa8)

**补充信息**
版本:13.0.1.315

**Comment by Snoopy1866** [comment]
建议提供快照

**Comment by yiwaaaa** [comment]
[1695779799732.zip](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/files/12733486/1695779799732.zip)
升级提示快照

**Comment by Snoopy1866** [comment]
https://github.com/gkd-kit/subscription/pull/419
