### ISSUE TITLE
[适配需求] 云闪付

### ISSUE THREAD

**Issue by yiwaaaa** [Snoopy1866/LiTiaotiao-Custom-Rules#119]
**App 名称** 云闪付

**广告界面（提供截图）（可选）**
1.更新弹窗
[1695689384689.zip](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/files/12720887/1695689384689.zip)

**补充信息**
添加任何你认为有助于适配的信息

**Comment by Snoopy1866** [comment]
https://github.com/gkd-kit/subscription/pull/398

**Comment by yiwaaaa** [comment]
开屏广告
[1695768913584.zip](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/files/12732436/1695768913584.zip)

**Comment by Snoopy1866** [comment]
https://github.com/gkd-kit/subscription/blob/d6f49462b93d8f1b375fa7877ff2b7bba75072c7/src/apps/com.unionpay.ts#L7-L17

开屏广告是有规则的，你这个界面是有跳过提示但实际没有跳过吗？

**Comment by yiwaaaa** [comment]
> https://github.com/gkd-kit/subscription/blob/d6f49462b93d8f1b375fa7877ff2b7bba75072c7/src/apps/com.unionpay.ts#L7-L17
> 
> 开屏广告是有规则的，你这个界面是有跳过提示但实际没有跳过吗？

这个先不管了吧，我这边开屏广告和更新都跳不过去的
