### ISSUE TITLE
支付宝12306

### ISSUE THREAD

**Issue by lunhui11** [Snoopy1866/LiTiaotiao-Custom-Rules#131]
### 请输入 误触/不执行规则 的界面的快照, 也可在后面补充其它信息

支付宝的12306会一直收起
![Uploading Screenshot_2023-09-29-17-58-36-417_com.eg.android.AlipayGphone.jpg…]()

**Comment by lunhui11** [comment]
就是12306 你只要点了城市选择返回了就一直右上角被收起

**Comment by Snoopy1866** [comment]
快照没有上传成功
