### ISSUE TITLE
酷安评论区广告无法彻底关闭

### ISSUE THREAD

**Issue by tianluoer** [Snoopy1866/LiTiaotiao-Custom-Rules#132]
![Screenshot_2023-10-02-15-48-00-158_com.coolapk.market.jpg](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/126933267/f3efca2f-e5f5-4cfa-852b-3269f5059789)

能不能自动选择不感兴趣关闭

**Comment by Snoopy1866** [comment]
建议上传此界面的快照

**Comment by tianluoer** [comment]
> 建议上传此界面的快照

- emm这啥不懂

**Comment by tianluoer** [comment]
@![酷安评论区广告.zip](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/files/12790988/default.zip)

酷安评论区广告

**Comment by Snoopy1866** [comment]
看了一下快照，似乎已经有规则了

**Comment by tianluoer** [comment]
> 看了一下快照，似乎已经有规则了，你用的是 gkd 吗？

用的是李跳跳

**Comment by tianluoer** [comment]
我再去试试

**Comment by tianluoer** [comment]
清除数据重新添加规则之后又可以了
