### ISSUE TITLE
米家app,点击我的,点击头像,进入个人资料.返回不了,禁用规则就正常了

### ISSUE THREAD

**Issue by mysll** [Snoopy1866/LiTiaotiao-Custom-Rules#135]
### 请输入 误触/不执行规则 的界面的快照, 也可在后面补充其它信息

米家app,点击我的,点击头像,进入个人资料.返回不了,禁用规则就正常了

**Comment by Snoopy1866** [comment]
https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/blob/27320e66e455cd7317afe59af31a8978d2c4e66d/C/com/com.X/com.xiaomi.smarthome/readme.md?plain=1#L1-L14

米家 app 规则已经删除，请更新规则，或使用 [gkd](https://github.com/gkd-kit/gkd)
