### ISSUE TITLE
微信小程序群报数，左上角有5秒钟，很烦，希望能搞一个规则

### ISSUE THREAD

**Issue by zwj19957969701** [Snoopy1866/LiTiaotiao-Custom-Rules#138]
### 请输入需要添加规则的界面的快照, 也可在后面补充其它信息

![995d49c983bcdf1ec769a2e25630add](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/129370439/49e3310e-b9d7-4b28-bfcd-b5154c08858f)

![07b84744b6340fd153bd7923079b3c6](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/129370439/18ac8b78-aca2-4b3c-82a9-172be77e9cfc)
这个l链接里面进去就有广告而且有五秒钟，很烦，每天我都得去写日精进

**Comment by zwj19957969701** [comment]
[1697808414824.zip](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/files/13054741/1697808414824.zip)
你看看

**Comment by Snoopy1866** [comment]
默认规则有，你需要手动启用这个规则。
![image](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/45487685/da07f941-ebb7-4941-bff6-2319f29424a9)
