### ISSUE TITLE
增加下youtobe的规则吧

### ISSUE THREAD

**Issue by wokula** [Snoopy1866/LiTiaotiao-Custom-Rules#14]
增加下youtobe的规则吧

**Comment by Snoopy1866** [comment]
奇怪，没发现什么广告啊，能否给一个视频链接？

**Comment by wokula** [comment]
晚点我截图给你看。就是在看视频过程中，插播的广告，一般正常播放5秒后，有个跳过广告。

**Comment by TianYu-00** [comment]
Youtube的话推荐用Youtube Revanced. 直接去除全部youtube 广告，甚至视频内的恰饭广告都能给你自动快进。
https://github.com/revanced/revanced-manager

来自Reddit的安装教学(打不开的话翻个墙)：
https://reddit.com/r/revancedapp/s/g7weTze6DN

基本操作是：
下载youtube revanced manager (用来添加补丁+打包)
下载vanced microg (用来登陆)
下载适合revanced manager的youtube版本apk
用revanced manager添加补丁并打包下载好的youtube apk
打包完直接安装就好了

**Comment by wokula** [comment]
![微信图片_20230829090430](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/23372812/fbb8b4dd-4183-4ce6-aed5-9bdf4a24d649)

**Comment by wokula** [comment]
上图的那个跳过广告。

**Comment by Snoopy1866** [comment]
#27

**Comment by guojiahao999** [comment]
确实我也需要

**Comment by ysjsgzq** [comment]
> ![微信图片_20230829090430](https://user-images.githubusercontent.com/23372812/263869764-fbb8b4dd-4183-4ce6-aed5-9bdf4a24d649.jpg)

这种情况，切换一下横竖屏，就跳过了

**Comment by tkjune** [comment]
> #27

这种方式需要触发一下界面刷新，就像文中说的，比如弹一下AutoJS的弹窗。另外一个跳屏APP倒是做到了检测画面，可能李跳现有规则机制还不行。

**Comment by Snoopy1866** [comment]
或许可以试试 [GKD](https://github.com/gkd-kit/gkd)

**Comment by Snoopy1866** [comment]
> > #27
> 
> 这种方式需要触发一下界面刷新，就像文中说的，比如弹一下AutoJS的弹窗。另外一个跳屏APP倒是做到了检测画面，可能李跳现有规则机制还不行。

或许可以试试 [GKD](https://github.com/gkd-kit/gkd)

**Comment by Snoopy1866** [comment]
https://github.com/gkd-kit/subscription#comgoogleandroidyoutube---youtube

**Comment by guojiahao999** [comment]
gkd app在哪下载啊

**Comment by Snoopy1866** [comment]
https://github.com/gkd-kit/gkd
