### ISSUE TITLE
微信公众号中的广告怎么屏蔽啊

### ISSUE THREAD

**Issue by SpadgerBoy** [Snoopy1866/LiTiaotiao-Custom-Rules#144]
### 请输入需要添加规则的界面的快照, 也可在后面补充其它信息

微信公众号中的广告怎么屏蔽啊，包括卡片视图的广告与文章内的广告

**Comment by Snoopy1866** [comment]
公众号中的广告无法跳过，应为关闭按钮与其他按钮共享同一个控件。无法实现精准点击跳过按钮，这跟酷安的开屏无法跳过是相同的原因。

类似问题如下：

- https://github.com/gkd-kit/subscription/issues/28
- https://github.com/gkd-kit/subscription/issues/274
- https://github.com/gkd-kit/subscription/issues/503
- https://github.com/gkd-kit/subscription/issues/732
- https://github.com/gkd-kit/subscription/issues/354
- https://github.com/gkd-kit/subscription/issues/502
