### ISSUE TITLE
为什么点开规则复制界面，全是空白呀？

### ISSUE THREAD

**Issue by viewfirst** [Snoopy1866/LiTiaotiao-Custom-Rules#147]
### 请输入 误触/不执行规则 的界面的快照, 也可在后面补充其它信息

为什么点开规则复制界面，全是空白呀？

**Comment by Snoopy1866** [comment]
![image](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/45487685/3a880f4b-276d-4cf6-9224-2364493f1016)

点这里，如果还是不行那就是你的网络有问题。
