### ISSUE TITLE
拷贝漫画

### ISSUE THREAD

**Issue by YacratesWyh** [Snoopy1866/LiTiaotiao-Custom-Rules#148]
### 请输入需要添加规则的界面的快照, 也可在后面补充其它信息

拷贝漫画会在第一个跳过后立刻弹出第二个广告造成跳转，一个x在右一个在左。尽管应用能分别自动跳但是会在交替的时候自动跳到第三方应用。

**Comment by YacratesWyh** [comment]
![1699010592370_100](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/8447769/84a600f6-b87f-4d8e-a3a0-870cea9e7f65)
![1699010595841_100](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/8447769/ace7ccd2-e9ed-4741-92e5-28be60bc805e)

**Comment by Snoopy1866** [comment]
你都捕获快照了为什么不上传呢
