### ISSUE TITLE
不是很方便复制到规则，所有弄了一个在线的页面，有点草率

### ISSUE THREAD

**Issue by ossso** [Snoopy1866/LiTiaotiao-Custom-Rules#15]
[https://ossso.github.io/LiTiaotiao-Custom-Rules/](https://ossso.github.io/LiTiaotiao-Custom-Rules/)

很草率的一个在线页面，方便复制规则；
源项目没有单独的Pages分支，提不了PR呀。

**Comment by Snoopy1866** [comment]
大佬，不是很懂啊，是不是我还得新建一个 username.github.io 仓库？

**Comment by Snoopy1866** [comment]
大佬，我新建了一个名为 gh-pages 的分支，这样就可以了吗

**Comment by ossso** [comment]
> 大佬，我新建了一个名为 gh-pages 的分支，这样就可以了吗

建一个空分支好些；  
或者你直接复制https://github.com/ossso/LiTiaotiao-Custom-Rules/tree/pages里面的index.html

**Comment by Snoopy1866** [comment]
大佬，我把gh-pages分支的文件都删了，现在应该可以了吧

**Comment by ossso** [comment]
已经推进了pages分支

**Comment by laynezhao09** [comment]
推荐一个复制的网站：https://airportal.cn/

**Comment by ossso** [comment]
> 推荐一个复制的网站：https://airportal.cn/

不是要获取文件的意思，是太长了，不好选中全部，不同的手机可能在操作选中全部内容的时候，交互不一样；我的手机就很难选中全部；李跳跳是输入框导入，不是文件导入。

**Comment by 0laynezhao0** [comment]
我知道你的意思，这个👆🏻有一个按钮可以一键复制全部内容。

**Comment by 0laynezhao0** [comment]
> > 推荐一个复制的网站：https://airportal.cn/
> 
> 不是要获取文件的意思，是太长了，不好选中全部，不同的手机可能在操作选中全部内容的时候，交互不一样；我的手机就很难选中全部；李跳跳是输入框导入，不是文件导入。

我知道你的意思，这个👆🏻有一个按钮可以一键复制所有内容。

**Comment by ossso** [comment]
> > > 推荐一个复制的网站：https://airportal.cn/
> > 
> > 
> > 不是要获取文件的意思，是太长了，不好选中全部，不同的手机可能在操作选中全部内容的时候，交互不一样；我的手机就很难选中全部；李跳跳是输入框导入，不是文件导入。
> 
> 我知道你的意思，这个👆🏻有一个按钮可以一键复制所有内容。

👍可以的，就是每次都得下载、上传、扫码、复制……
