### ISSUE TITLE
Y2002电音

### ISSUE THREAD

**Issue by 19973383** [Snoopy1866/LiTiaotiao-Custom-Rules#154]
### 请输入需要添加规则的界面的快照, 也可在后面补充其它信息

在酷安下载的 Y2002电音 此软件有超级多的弹屏广告跟摇一摇跳转
![Uploading Screenshot_20231108_231913_com.coolapk.market.jpg…]()
![Uploading Screenshot_20231108_231843_com.blueocean.musicplayer.jpg…]()

**Comment by Snoopy1866** [comment]
没有上传成功
