### ISSUE TITLE
怎么恢复默认？

### ISSUE THREAD

**Issue by wingswing1** [Snoopy1866/LiTiaotiao-Custom-Rules#155]
### 请输入 误触/不执行规则 的界面的快照, 也可在后面补充其它信息

试用了几天感觉不太理想，怎么恢复默认？APP卸载重装都没用

**Comment by Snoopy1866** [comment]
清除app数据

**Comment by wingswing1** [comment]
试过了，不行呀



---- 回复的原邮件 ----
| 发件人 | Kun ***@***.***> |
| 日期 | 2023年11月12日 19:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Snoopy1866/LiTiaotiao-Custom-Rules] 怎么恢复默认？ (Issue #155) |

清除app数据

**Comment by yinzhuoqun** [comment]
[{"volume_mode":false},{"is_main_switch_on":true},{"-973170826":"{\"popup_rules\":[{\"id\":\"=发送&+未选中,原图\",\"action\":\"=原图\"}],\"rid\":[\"w0x3\"]}"},{"fs_message":"派大星，我们一起去抓水母吧~:🐠🐡🦀"},{"exclude_from_recents":false},{"foreground_service":true},{"ltt_suggestions_a":false}]
