### ISSUE TITLE
微信订阅号消息界面的 发现 内容可以关闭吗

### ISSUE THREAD

**Issue by yuf19-2022** [Snoopy1866/LiTiaotiao-Custom-Rules#156]

**Comment by Snoopy1866** [comment]
默认订阅找一下微信的规则，需要手动开启，有一定概率误触。

**Comment by Snoopy1866** [comment]
可以发快照看一下

**Comment by Snoopy1866** [comment]
> [1699801075942.zip](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/files/13328379/1699801075942.zip)
非独立控件，GKD 暂不支持。
![image](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/45487685/d8478a7e-92b4-4081-99ba-6abf1d200548)

**Comment by Snoopy1866** [comment]
> [1699801109213.zip](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/files/13328380/1699801109213.zip)

可以导入本地规则使用，我认为这个地方的规则可能不适用于大对数用户，因此不打算将其纳入默认订阅，如果你需要纳入默认订阅，可以前往 https://github.com/gkd-kit/subscription/issues/new?assignees=&labels=&projects=&template=feature_request.yml 提交 PR。

```json5
{
  "id": "com.tencent.mm",
  "name": "微信",
  "groups": [
    {
      "key": 1,
      "name": "[ChangeMe]规则名称-2023-11-12 23:19:43",
      "desc": "[ChangeMe]本规则由GKD网页端审查工具生成",
      "rules": [
        {
          "activityIds": "com.tencent.mm.plugin.brandservice.ui.flutter.BizFlutterTLFlutterViewActivity",
          "matches": "[desc='展开更早的消息']",
          "snapshotUrls": "https://i.gkd.li/import/13328412"
        }
      ]
    }
  ]
}
```

**Comment by Snoopy1866** [comment]
可能是 activityId 的问题，可以将 activityId 置空以匹配任意 activity，复制下面的代码导入即可：

```json5
{
  "id": "com.tencent.mm",
  "name": "微信",
  "groups": [
    {
      "key": 1,
      "name": "[ChangeMe]规则名称-2023-11-12 23:19:43",
      "desc": "[ChangeMe]本规则由GKD网页端审查工具生成",
      "rules": [
        {
          "activityIds": [],
          "matches": "[desc='展开更早的消息']",
          "snapshotUrls": "https://i.gkd.li/import/13328412"
        }
      ]
    }
  ]
}
```
