### ISSUE TITLE
格式错误

### ISSUE THREAD

**Issue by A431HRZR** [Snoopy1866/LiTiaotiao-Custom-Rules#157]
### 请输入 误触/不执行规则 的界面的快照, 也可在后面补充其它信息

![Uploading Screenshot_2023-11-13-16-50-06-458_hello.litiaotiao.app.jpg…]()
![Uploading Screenshot_2023-11-13-16-50-10-301_hello.litiaotiao.app.jpg…]()

**Comment by Snoopy1866** [comment]
没有上传成功

**Comment by Snoopy1866** [comment]
另外，本项目不再更新李跳跳规则，请转移至 [gkd](https://github.com/gkd-kit/gkd)，谢谢！

**Comment by Snoopy1866** [comment]
导入格式错误的问题，请仔细查看本项目的主页下方的使用说明。
