### ISSUE TITLE
李跳跳规则，京东APP，购物车砸金蛋优惠券误杀，能屏蔽吗？

### ISSUE THREAD

**Issue by leiletter** [Snoopy1866/LiTiaotiao-Custom-Rules#158]
### 请输入 误触/不执行规则 的界面的快照, 也可在后面补充其它信息

如题，购物车砸金蛋弹出来的优惠券，大概是被误认为是广告弹窗了吧，会自动关闭。完全点不开

**Comment by Snoopy1866** [comment]
删除京东的规则即可
