### ISSUE TITLE
为什么不搞一个读取文件导入规则呢？小米烂手机根本复制不了全部文本

### ISSUE THREAD

**Issue by Glunefish** [Snoopy1866/LiTiaotiao-Custom-Rules#164]
### 请输入 误触/不执行规则 的界面的快照, 也可在后面补充其它信息

为什么不搞一个读取文件导入规则呢？小米烂手机根本复制不了全部文本

**Comment by Snoopy1866** [comment]
1. 首先我不是作者，我无法为李跳跳添加新功能
2. 关于复制长文本问题，请仔细查看Readme文件，如若不行请更换浏览器再次尝试复制（本人小米13，via浏览器可正常复制）

**Comment by Glunefish** [comment]
感谢，已经使用其它方法解决，该死的小米，故意整人



---原始邮件---
发件人: "Kun ***@***.***&gt;
发送时间: 2023年12月20日(周三) 晚上6:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Snoopy1866/LiTiaotiao-Custom-Rules] 为什么不搞一个读取文件导入规则呢？小米烂手机根本复制不了全部文本 (Issue #164)




  
首先我不是作者，我无法为李跳跳添加新功能
 
关于复制长文本问题，请仔细查看Readme文件，如若不行请更换浏览器再次尝试复制（本人小米13，via浏览器可正常复制）
