### ISSUE TITLE
新版晓晓优选开屏广告跳不过去了

### ISSUE THREAD

**Issue by BFGunslinger** [Snoopy1866/LiTiaotiao-Custom-Rules#166]
### 请输入需要添加规则的界面的快照, 也可在后面补充其它信息

![Uploading Screenshot_2024-01-08-21-12-27-486_moc.nauxuoyoaixoaix.www.jpg…]()

**Comment by BFGunslinger** [comment]
![Screenshot_2024-01-08-21-16-45-039_moc nauxuoyoaixoaix www](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/143425537/2a2da06b-fce2-400a-a20f-44277dabb11d)
![Screenshot_2024-01-08-21-12-27-486_moc nauxuoyoaixoaix www](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/143425537/d5d178a6-4162-4889-9d35-f61fc60cac4b)

**Comment by Snoopy1866** [comment]
请上传快照。
