### ISSUE TITLE
支付宝12306被强关

### ISSUE THREAD

**Issue by 846208921** [Snoopy1866/LiTiaotiao-Custom-Rules#167]
### 请输入 误触/不执行规则 的界面的快照, 也可在后面补充其它信息

1、打开支付宝
2、打开12306购票
3、选择地址
然后就会自动被收起了

**Comment by 846208921** [comment]
Uploading WeChat_20240110174812.mp4…

**Comment by Snoopy1866** [comment]
请上传快照

**Comment by 846208921** [comment]
![微信图片_20240110195317](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/59817780/527dee82-5de8-43c8-aaf8-09795929b162)
![微信图片_20240110195351](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/59817780/17a382d1-88bc-47ce-9f44-f068f16a4499)
![微信图片_20240110195357](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/59817780/2cbe79b8-787d-4729-aca4-dde144eb7289)
![微信图片_20240110195401](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/59817780/60e0785c-5204-42e5-95ed-3ff108adac14)

**Comment by 846208921** [comment]
选择完就字都被收起了

**Comment by 846208921** [comment]
选择完就自动被收起了

**Comment by Snoopy1866** [comment]
请上传快照而不是截图
