### ISSUE TITLE
李跳跳如何实现一天内只自动点击一次的规则

### ISSUE THREAD

**Issue by IDontUnderstand7** [Snoopy1866/LiTiaotiao-Custom-Rules#168]
大神好，想利用李跳跳实现打开阿里云盘/闲鱼/支付宝自动点击签到的功能，但是按照正常的点击逻辑，每次打开签到页面都会自动点击，想请问下有没有如果想实现一天内只自动点击一次，规则要怎么写？望解答，谢谢。

**Comment by Snoopy1866** [comment]
无法实现

**Comment by IDontUnderstand7** [comment]
好的，感谢解答
