### ISSUE TITLE
无法跳过爱奇艺体育APP的开屏广告

### ISSUE THREAD

**Issue by lancerwhite** [Snoopy1866/LiTiaotiao-Custom-Rules#171]
### 请输入 误触/不执行规则 的界面的快照, 也可在后面补充其它信息

用autojs识别bounds，新增规则仍旧无效，无法跳过开屏广告

**Comment by Snoopy1866** [comment]
请上传快照

**Comment by lancerwhite** [comment]
> 请上传快照

之前没细看，不好意思。不能适配李跳跳的规则了吗？gkd有点耗电
