### ISSUE TITLE
能更新es文件浏览器的规则吗？

### ISSUE THREAD

**Issue by Solitjay** [Snoopy1866/LiTiaotiao-Custom-Rules#18]

**Comment by Snoopy1866** [comment]
暂时没发现广告，能否提供一下页面截图，

**Comment by Snoopy1866** [comment]
[com.estrongs.android.pop](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/blob/main/C/com/com.E/com.estrongs.android.pop/readme.md)（ES文件浏览器）
