### ISSUE TITLE
一人血书，大师兄影视

### ISSUE THREAD

**Issue by fansangg** [Snoopy1866/LiTiaotiao-Custom-Rules#24]
大师兄影视弹窗的广告有点多...

**Comment by Snoopy1866** [comment]
Pangle SDK，请查看[无法适配列表](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/blob/main/_source/NotSupportedList/NotSupportedList.md)

**Comment by apgk** [comment]
找个去广告版本，或者直接上tvbox 配上源 ，github就有。
