### ISSUE TITLE
安装版本apk的文件大小只有100多k，明显不对啊，实测安装失败啊。

### ISSUE THREAD

**Issue by CatcaptainTeam** [Snoopy1866/LiTiaotiao-Custom-Rules#30]
请更新apk文件到可用版本。

**Comment by yangxiaoge** [comment]
> 请更新apk文件到可用版本。

你确定下载完整的apk了吗，文件大小3.06M，你网络不好吧。
![image](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/12471093/1c2e85c4-561f-443d-9413-65b6e21f7fc1)

**Comment by FW27623** [comment]
> 请更新apk文件到可用版本。
可尝试这个链接下载：

`https://ghproxy.com/https://raw.githubusercontent.com/Snoopy1866/LiTiaotiao-Custom-Rules/main/_source/PaiDaXing/litiaotiao-pdx2.2.apk`
