### ISSUE TITLE
[适配需求] App 名称

### ISSUE THREAD

**Issue by yanyudalao** [Snoopy1866/LiTiaotiao-Custom-Rules#32]
**请注意：基于 bounds 的规则不会被适配**

**两步路户外助手**

**开屏默认广告已经可以自动跳过，但在此界面的广告无法跳过**
广告图如下：
![image](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/50091215/a4aa1b7e-15a1-434d-8301-970c4ce75400)

**Comment by LinkStark** [comment]
请问可以适配一下微信和qq小程序的广告跳过吗

**Comment by Snoopy1866** [comment]
> 请问可以适配一下微信和qq小程序的广告跳过吗

小程序搞不了

**Comment by GGforceP** [comment]
> 请问可以适配一下微信和qq小程序的广告跳过吗

这个可以通过第三方的模块去除，效果更彻底

**Comment by Hunya2077** [comment]
c请问可以适配一下cctalk吗

**Comment by Snoopy1866** [comment]
> 

请提交 issue

**Comment by Snoopy1866** [comment]
> c请问可以适配一下cctalk吗

请提交 issue
