### ISSUE TITLE
穿山甲插屏

### ISSUE THREAD

**Issue by im-maning** [Snoopy1866/LiTiaotiao-Custom-Rules#34]
穿山甲的插屏广告，关闭按钮，根据"反馈"文字，找到父亲控件，在父亲控件下找到第一个子控件就是关闭按钮，不知道能不能写规则。

**Comment by Snoopy1866** [comment]
你是指字节那个穿山甲？

**Comment by Snoopy1866** [comment]
李跳跳应该没有这种规则

**Comment by im-maning** [comment]
是字节那个Pangle的，没有就不行了。

**Comment by Snoopy1866** [comment]
> 穿山甲的插屏广告，关闭按钮，根据"反馈"文字，找到父亲控件，在父亲控件下找到第一个子控件就是关闭按钮，不知道能不能写规则。

gkd：https://github.com/gkd-kit/gkd
gkd 订阅：https://github.com/gkd-kit/subscription
gkd 选择器：https://github.com/gkd-kit/selector

后续将逐步开始 gkd 的适配
