### ISSUE TITLE
酷安app信息流广告问题

### ISSUE THREAD

**Issue by qwerttvv** [Snoopy1866/LiTiaotiao-Custom-Rules#36]
信息流广告自动点关闭，之后会弹出一个反馈对话框，大意要你选择关闭广告原因

这样的话，刷着刷着，还要手动再点个反馈，就很难受

**Comment by Snoopy1866** [comment]
请提供截图，app版本。

**Comment by Snoopy1866** [comment]
> ![Screenshot_2023-09-01-09-23-28-36_97550f1d11c73369bbee8f7d47965447](https://user-images.githubusercontent.com/56712217/264839562-b7fd04da-d385-420b-ba33-9cbf339ac4fe.jpg) ![Screenshot_2023-09-01-09-23-07-94_97550f1d11c73369bbee8f7d47965447](https://user-images.githubusercontent.com/56712217/264839649-f5529953-09b8-4b78-8dd2-34b3a91d4d80.jpg)

加了一条规则，重新导入试试看

**Comment by Snoopy1866** [comment]
> 还有一些开屏没法儿关掉，也是这个版本的酷安
> 
> ![Screenshot_2023-09-01-11-07-06-47_97550f1d11c73369bbee8f7d47965447](https://user-images.githubusercontent.com/56712217/264908695-9922e621-c056-4a6f-9bfc-31729e253644.jpg)

这个开屏广告我暂时无法复现，好几天了都没见到开屏广告🤣

**Comment by Snoopy1866** [comment]
https://github.com/gkd-kit/subscription/issues/28
