### ISSUE TITLE
[适配需求] 这种订阅号

### ISSUE THREAD

**Issue by GGforceP** [Snoopy1866/LiTiaotiao-Custom-Rules#42]
**请注意：基于 bounds 的规则不会被适配**

**微信（Google商店版本）**

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。

**广告截图**
![Screenshot_20230903_191445_WeChat](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/46444542/f15a9948-3c97-49e1-b875-08b4235b15c5)

**补充信息**
微信订阅号底部广告和订阅号广告

**Comment by Snoopy1866** [comment]
{"popup_rules":[{"id":"广告","action":"feedbackIcon"},{"id":"dislike&feedbackBtn","action":"不感兴趣"},{"id":"isdismatch&isduplicate&isbadad","action":"与我无关"}],"ltt_service":true}

**Comment by Snoopy1866** [comment]
先暂时用这个规则吧，下一版再一起更新

**Comment by Snoopy1866** [comment]
这种也还是得手动触发一下，李跳跳对这种广告识别不是很灵敏

**Comment by GGforceP** [comment]
好！感谢大佬

**Comment by Snoopy1866** [comment]
已适配，请重新导入规则。[com.tencent.mm](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/blob/main/C/com/com.T/com.tencent.mm/readme.md)（微信）

**Comment by GGforceP** [comment]
感谢大佬！！
