### ISSUE TITLE
[bug反馈] 米家设置界面bug

### ISSUE THREAD

**Issue by yoyodadada** [Snoopy1866/LiTiaotiao-Custom-Rules#43]
导入全部规则后，进入米家APP-我的-设置，将自动点击自动发现设备界面，返回后仍将进入此界面，往规则编辑者修复此问题。
感谢！

**Comment by Snoopy1866** [comment]
可能是米家版本的问题，8.4.717 暂未发现此问题，请提供一下你的米家版本号。

**Comment by yoyodadada** [comment]
> 可能是米家版本的问题，8.4.717 暂未发现此问题，请提供一下你的米家版本号。

米家版本v8.8.705.2925，李跳跳版本-派大星2.2，规则导入时间2023.9.5，上述bug依旧存在。

**Comment by LiamNova** [comment]
确实能重现，同样问题

**Comment by Snoopy1866** [comment]
问题已复现，可以先禁用米家规则临时解决问题，下个版本修复。

**Comment by zl939144892** [comment]
修复了么？

**Comment by Snoopy1866** [comment]
> 修复了么？

还没呢，让bug先飞一会儿

**Comment by Snoopy1866** [comment]
经过查看控件ID，发现ID相较于上一版本有所变化，猜测该APP控件ID经过混淆，暂时移除了相关规则。

**Comment by Snoopy1866** [comment]
李跳跳适配不佳，已改用GKD。
 gkd-kit/subscription#86
