### ISSUE TITLE
[bug反馈] 

### ISSUE THREAD

**Issue by updain** [Snoopy1866/LiTiaotiao-Custom-Rules#48]
开源阅读获取备份文件夹权限时自动跳过无法点击允许
![Screenshot_2023-09-05-22-14-21-481_com google android documentsui](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/144141919/8179cdce-1998-41cb-a30f-b0a79db63bfb)

**Comment by updain** [comment]
测试时关闭开源阅读的跳跳设置也不能阻止

**Comment by updain** [comment]
谢谢建议，关闭李跳跳全局可以解除

**Comment by FW27623** [comment]
> 谢谢建议，关闭李跳跳全局可以解除

OK，那有可能是跳跳把哪个弹框给识别成广告了？仓库里确实是没有跟开源阅读相关的规则

**Comment by updain** [comment]
调用的是安卓框架文件，从手机文件管理进data的那个框架，不知道是不是这个，但在跳跳设置里没看到有这个系统软件
![Uploading IMG_20230905_231901.jpg…]()

**Comment by Snoopy1866** [comment]
![image](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/45487685/258820c5-ceb0-4546-af9f-4b9b63091baa)
是这个吧，增强规则里的，帮你点允许

**Comment by FW27623** [comment]
> ![image](https://user-images.githubusercontent.com/45487685/265748230-258820c5-ceb0-4546-af9f-4b9b63091baa.png) 是这个吧，增强规则里的，帮你点允许

感觉应该是这个

**Comment by updain** [comment]
是了，以前导入过增强的，后来导入了基础的，产生bug了，我清楚了一遍数据，重新导入基础的就好了

**Comment by updain** [comment]
还以为增强换基础直接导入就全部替换了
