### ISSUE TITLE
皮皮喵 开屏广告页面

### ISSUE THREAD

**Issue by Snoopy1866** [Snoopy1866/LiTiaotiao-Custom-Rules#5]
皮皮喵 开屏广告页面
com.gentle.ppcat

_Originally posted by @Meiico in https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/discussions/4#discussioncomment-6654575_

**Comment by Snoopy1866** [comment]
目测三层广告。
第一层使用 text 可跳过；
第二层右上角关闭按钮不是单独的控件，无法识别；
第三层右上角跳过，有5秒延迟，且倒计时开始前会检测网络连接，从连接网络到出现“剩余 x 喵”，消耗的时间未知。

**Comment by Snoopy1866** [comment]
目测三层广告。
第一层使用 text 可跳过；
第二层右上角关闭按钮不是单独的控件，且无法通过 GLOBAL_ACTION_BACK 跳过；
第三层右上角首先显示“喵喵载入中”，此时会连接网络，之后出现5秒倒计时，从喵喵载入到出现“剩余 x 喵”所消耗的时间未知。
@Meiico

**Comment by Meiico** [comment]
所以这个只能跳过第一层广告是嘛



---原始邮件---
发件人: "Kun ***@***.***&gt;
发送时间: 2023年8月7日(周一) 晚上8:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Snoopy1866/LiTiaotiao-Custom-Rules] 皮皮喵 开屏广告页面 (Issue #5)




 
目测三层广告。
 第一层使用 text 可跳过；
 第二层右上角关闭按钮不是单独的控件，且无法通过 GLOBAL_ACTION_BACK 跳过；
 第三层右上角首先显示“喵喵载入中”，此时会连接网络，之后出现5秒倒计时，从喵喵载入到出现“剩余 x 喵”所消耗的时间未知。
 @Meiico

**Comment by Snoopy1866** [comment]
应该是的，第二层广告应该是没法跳的，不知道有没有其他大佬可以实现跳过第三层广告。������



***@***.***
 
发件人： Meiico
发送时间： 2023-08-08 18:53
收件人： Snoopy1866/LiTiaotiao-Custom-Rules
抄送： Kun Jinkao; Author
主题： Re: [Snoopy1866/LiTiaotiao-Custom-Rules] 皮皮喵 开屏广告页面 (Issue #5)
所以这个只能跳过第一层广告是嘛 



---原始邮件--- 
发件人: "Kun ***@***.***&gt; 
发送时间: 2023年8月7日(周一) 晚上8:42 
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; 
主题: Re: [Snoopy1866/LiTiaotiao-Custom-Rules] 皮皮喵 开屏广告页面 (Issue #5) 





目测三层广告。 
第一层使用 text 可跳过； 
第二层右上角关闭按钮不是单独的控件，且无法通过 GLOBAL_ACTION_BACK 跳过； 
第三层右上角首先显示“喵喵载入中”，此时会连接网络，之后出现5秒倒计时，从喵喵载入到出现“剩余 x 喵”所消耗的时间未知。 
@Meiico

**Comment by Meiico** [comment]
好的，谢谢



---原始邮件---
发件人: "Kun ***@***.***&gt;
发送时间: 2023年8月8日(周二) 晚上7:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Snoopy1866/LiTiaotiao-Custom-Rules] 皮皮喵 开屏广告页面 (Issue #5)




 应该是的，第二层广告应该是没法跳的，不知道有没有其他大佬可以实现跳过第三层广告。������ 
 
 
 
 ***@***.*** 
   
 发件人： Meiico 
 发送时间： 2023-08-08 18:53 
 收件人： Snoopy1866/LiTiaotiao-Custom-Rules 
 抄送： Kun Jinkao; Author 
 主题： Re: [Snoopy1866/LiTiaotiao-Custom-Rules] 皮皮喵 开屏广告页面 (Issue #5) 
 所以这个只能跳过第一层广告是嘛  
 
 
 
 ---原始邮件---  
 发件人: "Kun ***@***.***&amp;gt;  
 发送时间: 2023年8月7日(周一) 晚上8:42  
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.******@***.***&amp;gt;;  
 主题: Re: [Snoopy1866/LiTiaotiao-Custom-Rules] 皮皮喵 开屏广告页面 (Issue #5)  
 
 
 
 
 
 目测三层广告。  
 第一层使用 text 可跳过；  
 第二层右上角关闭按钮不是单独的控件，且无法通过 GLOBAL_ACTION_BACK 跳过；  
 第三层右上角首先显示“喵喵载入中”，此时会连接网络，之后出现5秒倒计时，从喵喵载入到出现“剩余 x 喵”所消耗的时间未知。  
 @Meiico

**Comment by Snoopy1866** [comment]
与 NP管理器，大师兄影视 都是一类广告，无法适配。

**Comment by Snoopy1866** [comment]
已通过 gkd 适配完成。https://github.com/gkd-kit/subscription/pull/560

**Comment by Meiico** [comment]
大佬:
&nbsp; &nbsp; &nbsp; 我这边正常是使用平板的竖屏模式来操作这个软件的，在使用过程中发现第一个30s的广告没有自动跳过，之后的广告可以正常跳过，然后我使用手机操作是都可以正常跳过的，不知道有没有可以完善的方式
设备:小米平板6，红米k50u







---原始邮件---
发件人: "Kun ***@***.***&gt;
发送时间: 2023年10月10日(周二) 上午9:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Snoopy1866/LiTiaotiao-Custom-Rules] 皮皮喵 开屏广告页面 (Issue #5)




 
Closed #5 as completed.

**Comment by Snoopy1866** [comment]
https://github.com/gkd-kit/subscription/issues/new?assignees=&labels=&projects=&template=feature_request.yml
