### ISSUE TITLE
[适配需求] 两步路户外助手

### ISSUE THREAD

**Issue by RookieExaminer** [Snoopy1866/LiTiaotiao-Custom-Rules#52]
**请注意：基于 bounds 的规则不会被适配**

**App 名称** 
两步路户外助手

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。
com.lolaage.tbulu.tools

**广告界面（提供截图）（可选）**
如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；
打开APP，首页就会弹出这个广告，全部规则里别的可以跳过，这个跳不过去。希望可以适配
![_-1972738793__1d2c58d9c71f6189301703184006929d_36565048_Screenshot_2023-09-06-16-16-34-539_com lolaage tbulu tools_0_wifi_0](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/23047162/af33d1ee-42ca-4dd3-abb9-b553113c4bf9)

**补充信息**
添加任何你认为有助于适配的信息

**Comment by Snoopy1866** [comment]
#32
