### ISSUE TITLE
[适配需求] MX播放器 

### ISSUE THREAD

**Issue by guojiahao999** [Snoopy1866/LiTiaotiao-Custom-Rules#53]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**

MX播放器 mxplayer
**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。
com.mxtech.videoplayer.ad

**广告界面（提供截图）（可选）**
如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；
![微信图片_20230906191431](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/142034389/905efef3-01b8-4bb6-bc66-db33bd69ec12)

**补充信息**
添加任何你认为有助于适配的信息

**Comment by Snoopy1866** [comment]
已通过 [gkd](https://github.com/gkd-kit/gkd) 进行适配
https://github.com/gkd-kit/subscription/pull/117
