### ISSUE TITLE
[适配需求] 亲邻开门

### ISSUE THREAD

**Issue by yinsupercloud** [Snoopy1866/LiTiaotiao-Custom-Rules#55]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**
亲邻开门

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。

**广告界面（提供截图）（可选）**
如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；
![a9beae6acaf7fa9a6c3f28ae3d17a15](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/124701071/07f23c7c-9a22-4614-a7b5-fad250820858)

![6e8f518b1b8ce680716019f4c7392a2](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/124701071/e19a0466-3f32-4d40-a59c-e27ba0491406)

**补充信息**
添加任何你认为有助于适配的信息
麻烦麻烦大神帮忙，这个软件太流氓了，一开门就弹窗，这个软件用的人也很多

**Comment by Snoopy1866** [comment]
{"popup_rules":
    [
        {"id":"reaper_ad_source_layout","action":"close"},
        {"id":"adv_main","action":"iv_close"}
    ]
}

**Comment by Snoopy1866** [comment]
已适配，等待合并入主分支。
