### ISSUE TITLE
[适配需求] 豆瓣

### ISSUE THREAD

**Issue by xzpcjy** [Snoopy1866/LiTiaotiao-Custom-Rules#56]
**请注意：基于 bounds 的规则不会被适配**

**App 名称** 豆瓣

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。

**广告界面（提供截图）（可选）**
如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；
![Screenshot_2023-09-07-23-46-26-24_a3a62bdaa42478dfcfd65cf54dff2719](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/106061778/9779517b-c77f-4eaa-9cb9-9f797cec80a9)

**补充信息**
添加任何你认为有助于适配的信息

**Comment by Snoopy1866** [comment]
实测默认规则可以跳过豆瓣开屏广告，App 版本号 7.59.1，设备 Xiaomi 13 MIUI V14.0.23.9.5.DEV，无需自定义规则，请检查李跳跳相关设置是否开启。

**Comment by Snoopy1866** [comment]
建议使用 [gkd](https://github.com/gkd-kit/gkd)
