### ISSUE TITLE
微信小程序

### ISSUE THREAD

**Issue by Anhai0501** [Snoopy1866/LiTiaotiao-Custom-Rules#57]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**
微信小程序

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。

**广告界面（提供截图）（可选）**
如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；
![f436588bb5344e965007034d02d5b88](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/99585202/60a9f85f-dfe6-47cc-a658-f0f5502a91a4)

**补充信息**
添加任何你认为有助于适配的信息

**Comment by Snoopy1866** [comment]
跳过按钮没有任何可标识文本，无法适配

**Comment by Anhai0501** [comment]
![微信图片_20230915210335](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/99585202/dc402198-b4e1-4659-bf3e-175dffb4cd95)
这个能行吗 朋友圈的

**Comment by Snoopy1866** [comment]
我是用的是 Google Play Store 的微信，并没有朋友圈广告，暂时无法复现，抱歉。
