### ISSUE TITLE
[适配需求] 豆瓣

### ISSUE THREAD

**Issue by jnlpc123** [Snoopy1866/LiTiaotiao-Custom-Rules#58]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**
豆瓣

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。
com.douban.frodo

**广告界面（提供截图）（可选）**
如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；
![Screenshot_2023-09-08-08-49-41-947_com douban frodo](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/57972366/1fbc2041-a137-463a-a266-e6b34451c78d)
![Screenshot_2023-09-08-08-50-40-425_com douban frodo](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/57972366/4e71a17b-c804-4299-8dae-585b6f575278)

开屏广告及信息流广告

**补充信息**
添加任何你认为有助于适配的信息

**Comment by Snoopy1866** [comment]
#56

**Comment by Snoopy1866** [comment]
{"popup_rules":
    [
        {"id":"新版试用","action":"取消"},

        {"id":"ad_download","action":"ad_not_interest"},
        {"id":"不感兴趣&投诉","action":"不感兴趣"},

        {"id":"push_tip_title","action":"close_tip"},

        {"id":"ad_header_new","action":"menu_item"}
    ]
}

**Comment by Snoopy1866** [comment]
```
{"popup_rules":
    [
        {"id":"新版试用","action":"取消"},

        {"id":"ad_download","action":"ad_not_interest"},
        {"id":"不感兴趣&投诉","action":"不感兴趣"},

        {"id":"push_tip_title","action":"close_tip"},

        {"id":"ad_header_new","action":"menu_item"}
    ]
}
```

**Comment by Snoopy1866** [comment]
信息流广告已适配，等待合并入主分支。
