### ISSUE TITLE
关于APP包名ID生成算法

### ISSUE THREAD

**Issue by AdminHcat** [Snoopy1866/LiTiaotiao-Custom-Rules#6]
> 由于 “李跳跳” 导出的规则中，每个 app 名称都使用一串 id 进行代替，本人才疏学浅，暂未获取到这个 id 的算法，因此本项目目前采用的是单个 app 一份规则文件的结构，需要对每个 app 单独导入规则。有懂的大佬可以告知一下这个 id 的算法。

特此去逆向了一下，希望对规则维护有所帮助，关于此id的生成仅仅只是对包名字符串进行简单的hashCode
字符串对象的哈希码根据以下公式计算：
`s[0]*31^(n-1) + s[1]*31^(n-2) + ... + s[n-1]`

![image](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/50044729/efb1ce65-3174-443d-933f-683e1cadc888)

**Comment by Snoopy1866** [comment]
感谢，后期准备根据这个算法生成单独一份规则文件，方便一键导入。🤗

**Comment by Snoopy1866** [comment]
已生成 java 程序，感谢大佬提供算法。
