### ISSUE TITLE
[适配需求] 喜马拉雅

### ISSUE THREAD

**Issue by implanb** [Snoopy1866/LiTiaotiao-Custom-Rules#62]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**
喜马拉雅

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。
com.ximalaya.ting.android

**广告界面（提供截图）（可选）**
如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；
![Screenshot_2023-09-10-01-42-40-151_com ximalaya ting android](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/80632042/f1b96896-c9dc-493c-a5d8-4d0039b7ed92)

**补充信息**
添加任何你认为有助于适配的信息
开启青少年模式

**Comment by implanb** [comment]
> **请注意：基于 bounds 的规则不会被适配**
> 
> **App 名称** 喜马拉雅
> 
> **App 包名（可选）** 如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。 com.ximalaya.ting.android
> 
> **广告界面（提供截图）（可选）** 如未提供截图，则尽可能适配容易触发的广告界面； 如广告界面隐藏较深，建议提供复现步骤； ![Screenshot_2023-09-10-01-42-40-151_com ximalaya ting android](https://user-images.githubusercontent.com/80632042/266795424-f1b96896-c9dc-493c-a5d8-4d0039b7ed92.jpg)
> 
> **补充信息** 添加任何你认为有助于适配的信息 开启青少年模式

**Comment by Snoopy1866** [comment]
暂时无法复现，复现了的大佬可以提个pr

**Comment by implanb** [comment]
李跳跳有个自带的青少年弹窗屏蔽，开了后还没出现过
