### ISSUE TITLE
[适配需求] 高德地图

### ISSUE THREAD

**Issue by yuf19-2022** [Snoopy1866/LiTiaotiao-Custom-Rules#63]
**请注意：基于 bounds 的规则不会被适配**

**高德地图**

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。

**广告界面（提供截图）（可选）**
![Screenshot_20230910_113247.jpg](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/109777030/af24add8-edc3-45a0-b4ef-5e1a062c1d9d)

如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；

**补充信息**
添加任何你认为有助于适配的信息

**Comment by Snoopy1866** [comment]
这个版本更新弹窗似乎不对劲

**Comment by Snoopy1866** [comment]
能否提供高德地图的版本号，如果可以，请你正在使用的版本的下载链接。

**Comment by Snoopy1866** [comment]
```
{"popup_rules":
    [
        {"id":"立即升级","action":"iv_close"},
        {"id":"版本升级","action":"取消"},
        {"id":"msgbox_popup_clear","action":"msgbox_popup_clear"}
    ]
}
```

先试试这个规则。
