### ISSUE TITLE
[适配需求] 美团－首页－拼好饭

### ISSUE THREAD

**Issue by yuf19-2022** [Snoopy1866/LiTiaotiao-Custom-Rules#64]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。

**广告界面（提供截图）（可选）**
![Screenshot_20230910_113550.jpg](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/109777030/4db0a4da-1680-4d9f-ae3c-beb4d0e8dd20)

![Screenshot_20230910_113800.jpg](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/109777030/f5d2dc67-9b32-4608-9dfd-4563aa797590)

如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；

**补充信息**
添加任何你认为有助于适配的信息

**Comment by Snoopy1866** [comment]
关闭按钮无任何可标识文本，且无法通过返回键关闭，暂时无法适配。
