### ISSUE TITLE
[适配需求] 中国移动云盘

### ISSUE THREAD

**Issue by yuf19-2022** [Snoopy1866/LiTiaotiao-Custom-Rules#65]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。

**广告界面（提供截图）（可选）**
![Screenshot_20230910_123836.jpg](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/109777030/1108e28f-edcf-4b0e-a707-195a1f1cc8f4)

如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；

**补充信息**
添加任何你认为有助于适配的信息

**Comment by Snoopy1866** [comment]
已适配，等待合并入主分支。
