### ISSUE TITLE
酷安跳广告问题

### ISSUE THREAD

**Issue by FeyWAnGG** [Snoopy1866/LiTiaotiao-Custom-Rules#67]
导入了增强规则，酷安的开屏广告有时候没反应了，只能等手动点跳过，另外进入浏览后，一闪而过不知道是否点了广告和取消，但是没什么效果，该有的还是有，建议再看一下规则是否合适，感谢

**Comment by Snoopy1866** [comment]
1. 增强规则中并没有酷安的规则
2. 基础规则中的酷安会在布局切换的时候帮你关闭评论区的广告，但是滑动评论区动态加载的广告不会自动跳过，这是李跳跳识别广告原理的局限性

**Comment by FeyWAnGG** [comment]
前面表述错了，就是0904更新的基础规则（或全部规则，前面说错成增强规则了）中是包含酷安的，但我不太明白所谓的“布局切换”是什么场景。我的问题是，酷安的开屏广告不知道什么原因，经常不能正常关闭。酷安的开屏广告是有关闭按钮的，有时候还有倒计时，即“关闭 5”，“关闭4”这样，有时候似乎是只有关闭两字，不知道是不是这个原因，导致李跳跳默认规则+0904基础规则下，经常关闭不了开屏广告，麻烦看一下，谢谢

**Comment by Snoopy1866** [comment]
https://github.com/gkd-kit/subscription/issues/28

请看酷安开屏广告的快照，跳过按钮并不是单独的控件，是嵌入整个广告界面的，你看到的“关闭”文字实际上并不是控件本身的属性，所以李跳跳无法跳过，由于不是单独的控件，gkd 对此也无能为力。不过作者说后续会加上相对位置点击，可以先观望一下。

**Comment by FeyWAnGG** [comment]
好的，这么说我明白了，感谢
