### ISSUE TITLE
[适配需求] 遥控精灵

### ISSUE THREAD

**Issue by chunmengtu** [Snoopy1866/LiTiaotiao-Custom-Rules#68]
**App 名称**：遥控精灵

**App 包名（可选）**：com.tiqiaa.icontrol

**广告界面（提供截图）（可选）**
![dc350cc38427d30a200d7fed39a173b6](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/85140496/c7e672f4-86a5-4c35-906d-c601523beb24)

**补充信息**
李跳跳虽然显示已经跳过，但广告实际上并没有被跳过

**Comment by Snoopy1866** [comment]
实测默认规则可以跳过遥控精灵开屏广告，App 版本号 5.7.1，设备 Xiaomi 13 MIUI V14.0.23.9.5.DEV，无需自定义规则，请检查李跳跳相关设置是否开启。

**Comment by Snoopy1866** [comment]
已通过 [gkd](https://github.com/gkd-kit/gkd) 进行适配。
https://github.com/gkd-kit/subscription/pull/116
