### ISSUE TITLE
[适配需求] 趣网咖

### ISSUE THREAD

**Issue by palmcivetcn** [Snoopy1866/LiTiaotiao-Custom-Rules#69]
**趣网咖**

**App 包名：com.ywkj.qwk**

**广告界面**
如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；
![Screenshot_20230912_213156_com.ywkj.qwk_edit_130456627266030.jpg](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/101246104/00be4ef2-381d-4afa-8636-98891c7cdf69)

**补充信息**
期待适配🥰

**Comment by Snoopy1866** [comment]
很抱歉，这是腾讯优量汇 SDK 的广告，无法适配。[无法适配的 App 列表](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/blob/main/_source/NotSupportedList/NotSupportedList.md)
