### ISSUE TITLE
微信小程序弹窗广告

### ISSUE THREAD

**Issue by Jony-2018** [Snoopy1866/LiTiaotiao-Custom-Rules#7]
请问打开微信小程序后弹出来的广告能关闭吗？

例如当前小程序是《接龙》小程序，打开小程序后，会优先弹出一个广告，需要等待几秒或者点击跳过才广告才会关闭。

![微信图片_20230816163111](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/51848340/30b40f2b-a204-4a73-8a5e-449786ffd794)

**Comment by Snoopy1866** [comment]
获取不到控件的任何有效标识符（desc, text, id），无法跳过。
