### ISSUE TITLE
[适配需求] 墨迹天气

### ISSUE THREAD

**Issue by iiauaf** [Snoopy1866/LiTiaotiao-Custom-Rules#70]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。

**广告界面（提供截图）（可选）**
如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；

**补充信息**
添加任何你认为有助于适配的信息

**Comment by Snoopy1866** [comment]
可适配的弹窗不多，目前看来还是比较干净的。
```
{"popup_rules":
    [
        {"id":"开始发图","action":"GLOBAL_ACTION_BACK"},
        {"id":"签到成功","action":"close"}
    ]
}
```

**Comment by Snoopy1866** [comment]
等待合并入主分支。
