### ISSUE TITLE
[适配需求] 蜻蜓FM

### ISSUE THREAD

**Issue by HarveyhyphenYuan** [Snoopy1866/LiTiaotiao-Custom-Rules#71]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**
蜻蜓FM

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。

**广告界面（提供截图）（可选）**
如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；
第一个广告：播放任意节目，在播放控制器和评论区中间有广告块，第一天安装不会出现广告，从第二天开始摇一摇广告和普通广告轮番出现。
第二个广告，播放节目时锁屏，再打开全屏摇一摇广告

**补充信息**
添加任何你认为有助于适配的信息
刚谢大佬，实在是不好截图放在桌子上滑动都能跳转app，跳转后广告直接消失，想去应用商店举报都没法截图

**Comment by Snoopy1866** [comment]
等待复现开屏广告。

**Comment by HarveyhyphenYuan** [comment]
谢谢大佬

**Comment by Snoopy1866** [comment]
已通过 gkd 适配。https://github.com/gkd-kit/subscription/pull/98
