### ISSUE TITLE
[适配需求] 小米应用商店

### ISSUE THREAD

**Issue by admans** [Snoopy1866/LiTiaotiao-Custom-Rules#80]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**
小米应用商店

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。
com.xiaomi.market

**广告界面（提供截图）（可选）**
如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；
![应用商店广告](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/10204234/6c80b560-247b-430b-9424-ecaa118778ff)

**补充信息**
添加任何你认为有助于适配的信息
在应用设置内关闭通知后，每次手动更新app都会弹出这样的窗口，可以直接返回关闭，也可点击“X”关闭。

**Comment by Snoopy1866** [comment]
无法复现，建议提供gkd快照。https://github.com/gkd-kit/gkd
<img width="5973" alt="GKD快照分享图片教程" src="https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/45487685/f4772597-09af-4610-a090-def72d1019ee">

**Comment by admans** [comment]
> 无法复现，建议提供gkd快照。https://github.com/gkd-kit/gkd <img alt="GKD快照分享图片教程" width="2000" src="https://user-images.githubusercontent.com/45487685/270205194-f4772597-09af-4610-a090-def72d1019ee.png">
[1695625664163.zip](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/files/12712575/1695625664163.zip)

**Comment by Snoopy1866** [comment]
https://github.com/gkd-kit/subscription/pull/362

**Comment by Snoopy1866** [comment]
已适配，请等待默认订阅更新后可用，此规则默认关闭，需手动开启
