### ISSUE TITLE
[适配需求] 懂球帝

### ISSUE THREAD

**Issue by feilifeijia** [Snoopy1866/LiTiaotiao-Custom-Rules#81]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**
懂球帝

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。

**广告界面（提供截图）（可选）**
如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；
![Screenshot_20230915_135236](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/121727446/e20e0690-33d6-4e7b-9c16-128345a87354)
在app中浏览页面一段时间后会自动弹出广告，当前规则下无法自动关闭

**补充信息**
添加任何你认为有助于适配的信息

**Comment by Snoopy1866** [comment]
类似的穿山甲弹窗，李跳跳实际上是无能为力的，首先它的关闭按钮没有id，没有desc，没有text，且返回键无法关闭，因此 ACTION_GLOBAL_BACK 也无能为力。不过，你可以试试另一款跳广告 app：https://github.com/gkd-kit/gkd

我已经将规则写好，实测可以关闭，你可以试试，或者可以等待我去提交 PR

```
FrameLayout[desc^="webview-close"] > View
```

**Comment by Snoopy1866** [comment]
gkd-kit/subscription#85
