### ISSUE TITLE
[适配需求] 麻雀省钱

### ISSUE THREAD

**Issue by yhlnac** [Snoopy1866/LiTiaotiao-Custom-Rules#84]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**
麻雀省钱

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。
com.maque.app

**广告界面（提供截图）（可选）**
如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；
![微信图片_20230915221705](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/97741385/36b0fea4-5192-460f-a068-2bae0c3f144e)

**补充信息**
添加任何你认为有助于适配的信息

**Comment by Snoopy1866** [comment]
没有 id, text, desc，无法书写通用规则，建议通过 bounds 自行适配，或者使用 https://github.com/gkd-kit/gkd

**Comment by Snoopy1866** [comment]
已适配 gkd 规则：gkd-kit/subscription#94
