### ISSUE TITLE
[适配需求] 起点读书

### ISSUE THREAD

**Issue by yuf19-2022** [Snoopy1866/LiTiaotiao-Custom-Rules#85]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。

**广告界面（提供截图）（可选）**
![Screenshot_20230915_222445.jpg](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/109777030/2da3388b-97e7-4fe0-82bc-d2ce2603f307)

如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；

**补充信息**
添加任何你认为有助于适配的信息

**Comment by Snoopy1866** [comment]
这是哪个版本？

**Comment by Snoopy1866** [comment]
暂时使用 gkd 进行了初步适配。https://github.com/gkd-kit/subscription/pull/95

**Comment by Snoopy1866** [comment]
这个版本更新弹窗暂时无法复现，可以用 gkd 截一个快照给我。
