### ISSUE TITLE
[适配需求] 网易新闻

### ISSUE THREAD

**Issue by ackurdeeve** [Snoopy1866/LiTiaotiao-Custom-Rules#86]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**
网易新闻

**App 包名（可选）**
安卓版

**补充信息**
广告和关闭都有id，点关闭后会弹出新窗口idHex("0x7f091496")，不感兴趣，即可关闭广告。

**Comment by Snoopy1866** [comment]
李跳跳适配不佳，已适配 gkd 规则。

gkd-kit/subscription#92
