### ISSUE TITLE
[适配需求] 邮储银行

### ISSUE THREAD

**Issue by yuf19-2022** [Snoopy1866/LiTiaotiao-Custom-Rules#89]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。

**广告界面（提供截图）（可选）**
![Screenshot_20230916_205613.jpg](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/109777030/8a32f858-e8c7-47bd-babc-fe056e5f2597)

如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；
邮储银行-生活-政务便民-电子社保卡-我的电子社保卡

**补充信息**
添加任何你认为有助于适配的信息

**Comment by Snoopy1866** [comment]
我无法触发这个界面，建议提供一下快照，我用 gkd 适配一下

**Comment by Snoopy1866** [comment]
这个快照的图片是空白的，麻烦重新打一个快照。
![image](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/45487685/e60d9bf8-eaa3-4914-9c0e-46f570adb870)

**Comment by Snoopy1866** [comment]
猜测规则可能是 `[id="com.yitong.mbank.psbc:id/iv_theme"] + [id="com.yitong.mbank.psbc:id/iv_theme_close_btn"]`，不过因为快照空白，暂时不加入规则。

**Comment by Snoopy1866** [comment]
可能是手机限制了，或者app不允许截图，快照依然是空白的

**Comment by Snoopy1866** [comment]
> ![Screenshot_20230917_075919.jpg](https://user-images.githubusercontent.com/109777030/268476740-a8d5f3c1-1eb7-44f2-8da9-2c31962cc0ff.jpg)

我拿这张截图替换了，可行。🤣

**Comment by Snoopy1866** [comment]
- https://github.com/gkd-kit/subscription/pull/495
