### ISSUE TITLE
跳跳要没了 作者还会继续更新规则吗？

### ISSUE THREAD

**Issue by wy2919** [Snoopy1866/LiTiaotiao-Custom-Rules#9]

**Comment by Snoopy1866** [comment]
会吧，也许。。。李跳跳现在还是能用的。😥

**Comment by dawnflyc** [comment]
我担心停止更新了 然后狗日的再更新更新 然后彻底无效了

**Comment by Levi-Rem** [comment]
能联系上作者 开源么

**Comment by egmkang** [comment]
能让作者开源一下么, 这软件挺好用的

**Comment by cxw620** [comment]
> 能让作者开源一下么, 这软件挺好用的

毕竟狗tx没啥下限的, 开源也会被 DMCA, 对作者来说吃力不讨好, 还是不要叨扰作者, 当然我也很希望开源, 毕竟星星之火可以燎原.

**Comment by Aloys233** [comment]
其实只要规则一直更新就行

**Comment by wei-z-git** [comment]
祈祷一直能用
![FC807035](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/32572815/efe94d15-569f-4497-b662-e138f600c871)

**Comment by lazysang** [comment]
感谢腾讯发函宣传一波，让我了解到了如此好用的APP

**Comment by egmkang** [comment]
> 感谢腾讯发函宣传一波，让我了解到了如此好用的APP

是腾讯发的律师函让这么多跳跳下架的

**Comment by Snoopy1866** [comment]
> 这是逆向工程？ 挺强

想多了，自定义规则而已，我连bug都不会写，更别说逆向了。😥

**Comment by xyw0214** [comment]
兄弟这不是基本上一直在更新嘛。只要更新规则就是一直都能用其实。辛苦了！

**Comment by Snoopy1866** [comment]
由于李跳跳自定义规则的局限性，后续更新频率会降低，重心转移至 [gkd](https://github.com/gkd-kit/gkd) 的规则适配上。

**Comment by xyw0214** [comment]
搞快点APP和李跳跳一起用不是挺好的吗？不要想李跳跳更新了，作者都被律师函了
