### ISSUE TITLE
[适配需求] QQ

### ISSUE THREAD

**Issue by yuf19-2022** [Snoopy1866/LiTiaotiao-Custom-Rules#90]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。

**广告界面（提供截图）（可选）**
![Screenshot_20230917_091216.jpg](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/109777030/d2636ef2-8eae-4cb1-8229-d0a6c2e7916e)

如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；

**补充信息**
添加任何你认为有助于适配的信息

**Comment by Snoopy1866** [comment]
已通过 gkd 适配。https://github.com/gkd-kit/subscription/pull/114
