### ISSUE TITLE
[适配需求] 微信

### ISSUE THREAD

**Issue by 2890631861** [Snoopy1866/LiTiaotiao-Custom-Rules#92]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**
微信

**App 包名（可选）**
com.tencent.mm

**广告界面（提供截图）（可选）**
![Screenshot_2023-09-17-17-24-00-378_com.tencent.mm.jpg](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/144091152/00746d06-160c-4069-9a94-1d8a7a3bbf1e)

**补充信息**
gkd bug，朋友圈广告点开到如图页面就不动了

**Comment by Snoopy1866** [comment]
请提供一下这个界面的快照

**Comment by 2890631861** [comment]
> 请提供一下这个界面的快照

![1694944308013.zip](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/files/12642532/1694944308013.zip)

![1694944303457.zip](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/files/12642534/1694944303457.zip)

**Comment by Snoopy1866** [comment]
已提交 PR。https://github.com/gkd-kit/subscription/pull/118

**Comment by 2890631861** [comment]
> 已提交 PR。https://github.com/gkd-kit/subscription/pull/132

此项目出现问题，在点击两次后还剩下一个界面未点击
如图
![Screenshot_2023-09-18-01-39-47-158_com.tencent.mm.jpg](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/144091152/53435573-d65a-4a32-aa7d-2d419be2e688)

以下是快照
![1694972418889.zip](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/files/12643356/1694972418889.zip)
