### ISSUE TITLE
[适配需求] 7天澳門統考

### ISSUE THREAD

**Issue by Askdelphi** [Snoopy1866/LiTiaotiao-Custom-Rules#93]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**
7天澳門統考

**App 包名（可选）**
com.daysko.safp
https://play.google.com/store/apps/details?id=com.daysko.safp
**广告界面（提供截图）（可选）**
全是Google的广告，广告关闭按钮有有几种：
1、左上角：点跳过视频后，再点X才能关闭广告；
2、右上角：点跳过视频后，再点X才能关闭广告；
3、视频无法跳过，只能看完整个视频，才会出现X按钮
4、在广告左下方直接出现“关闭”按钮
5、在右上角直接出现X按钮
部分广告截图：
![微信图片_20230917204918](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/22807898/15c46804-edee-4814-9185-0b7da868ed2f)
![微信图片_20230917204936](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/22807898/cdf79a84-b569-484b-a0ac-4ae11d3c80ae)
![微信图片_20230917205000](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/22807898/1aeba1b7-d90e-47bc-8af3-3af596098676)
![微信图片_20230917205006](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/22807898/153b4f1d-9fbd-41ea-84a1-da9f904790ba)
![微信图片_20230917205011](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/22807898/d8fb7d7d-c91a-4ce7-aaea-db913353cd91)
![微信图片_20230917205017](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/22807898/a82f1dad-2a36-47ec-ab9c-b8028e956810)
![微信图片_20230917205024](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/22807898/e5d58a81-6672-42a0-bcfe-c6cc0420d980)
![微信图片_20230917205032](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/22807898/e9983792-745a-4125-9db1-6a7d34bd7b39)
![微信图片_20230917205035](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/22807898/4503f0e1-4392-45c1-9422-01dde9302a03)

**补充信息**
这个App广告出现得太丧心病狂，每做三个题目就出现广告，实在受不了了。

**Comment by Snoopy1866** [comment]
这个广告，由于关闭按钮不是独立控件，因此无法适配
![image](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/45487685/b1330ff5-aae5-4ce3-917f-3ed0417eb045)

**Comment by Snoopy1866** [comment]
大部分都适配了，底部广告难以适配，可以自己点一下，后面就没有了。

https://github.com/gkd-kit/subscription/pull/136
