### ISSUE TITLE
[适配需求] 美团

### ISSUE THREAD

**Issue by yuf19-2022** [Snoopy1866/LiTiaotiao-Custom-Rules#95]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。

**广告界面（提供截图）（可选）**
![Screenshot_20230918_192345.jpg](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/109777030/be9b14f7-ffe0-49d4-8cc2-095f20268796)

如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；

**补充信息**
添加任何你认为有助于适配的信息

**Comment by Snoopy1866** [comment]
https://github.com/gkd-kit/subscription/blob/main/src/apps/com.sankuai.meituan.takeoutnew.ts

**Comment by Snoopy1866** [comment]
https://github.com/gkd-kit/subscription#comsankuaimeituantakeoutnew---%E7%BE%8E%E5%9B%A2%E5%A4%96%E5%8D%96

**Comment by Snoopy1866** [comment]
对应李跳跳规则：
```
{id="wm_upgrade_force_cancel",action="wm_upgrade_force_cancel"}，
{id="update_title",action="btn_close"}
```
