### ISSUE TITLE
[适配需求] 求适配百度贴吧和知乎

### ISSUE THREAD

**Issue by 3m1nHY** [Snoopy1866/LiTiaotiao-Custom-Rules#96]
**请注意：基于 bounds 的规则不会被适配**

**App 名称**
百度贴吧
知乎

**App 包名（可选）**
如未提供包名，则默认根据应用市场搜索结果中最相关的 App 进行适配，可能会导致错误适配。

**广告界面（提供截图）（可选）**
如未提供截图，则尽可能适配容易触发的广告界面；
如广告界面隐藏较深，建议提供复现步骤；

贴吧就是帖子里信息流，还有首页推荐
知乎就是问题里的信息流，首页推荐

**补充信息**
添加任何你认为有助于适配的信息

**Comment by Snoopy1866** [comment]
建议使用 gkd，李跳跳对于应用内的信息流广告适配不佳。
gkd: https://github.com/gkd-kit/gkd
gkd默认订阅：https://github.com/gkd-kit/subscription
