### ISSUE TITLE
[适配需求] pu口袋校园

### ISSUE THREAD

**Issue by longzho** [Snoopy1866/LiTiaotiao-Custom-Rules#97]
**pu口袋校园**

**
![Screenshot_20230919_113739](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/118370548/265bd4ac-c1c4-4b6f-aae6-4e1b1d42edb1)
**

**
![Screenshot_20230919_113759](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/118370548/e7ce679e-3727-48b2-b056-4fae66e17bc7)
**

**补充信息**
![Screenshot_20230919_113849](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/118370548/b3da0541-d9e2-48bd-b0c3-35e84ad30369)

哪位大佬帮帮忙🙏页内广告太多了，LTT自带的只能跳过开屏广告😭

**Comment by Snoopy1866** [comment]
已通过 [gkd](https://github.com/gkd-kit/gkd) 进行适配：https://github.com/gkd-kit/subscription/pull/149

**Comment by Snoopy1866** [comment]
建议切换至 gkd 使用

**Comment by longzho** [comment]
只会按教程的小废物表示完全不会😭

**Comment by Snoopy1866** [comment]
进这个界面，下载apk，安装就行了。https://github.com/gkd-kit/gkd/releases

![image](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/assets/45487685/46062108-03a0-4475-89c9-4e728398bba0)

**Comment by longzho** [comment]
谢谢😋😘
